### ISSUE TITLE
Client wont work with self signed demo certificates

### ISSUE THREAD

**Issue by biancode** [node-opcua/node-opcua-pki#6]
Hello Etienne,

I've tested with that module to generate server and client certificates and key pairs.
The server works great with that:

![image](https://user-images.githubusercontent.com/4369867/36498699-62b0db6c-173f-11e8-8a61-8218622cfb94.png)

... but the client wont work, because of an error 

![image](https://user-images.githubusercontent.com/4369867/36498621-21971b6e-173f-11e8-969e-c2609486ae72.png)

`server_secure_channel_layer   :114   xxxxx error  SIGN and ENCRYPT asymmetricVerify : Invalid packet signature Error: SIGN and ENCRYPT asymmetricVerify : Invalid packet signature
    at MessageBuilderBase._report_error (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/message_builder_base.js:217:24)
    at MessageBuilder._decrypt_OPN (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-secure-channel/src/message_builder.js:185:14)
    at MessageBuilder._decrypt (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-secure-channel/src/message_builder.js:323:21)
    at MessageBuilder._read_headers (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-secure-channel/src/message_builder.js:368:19)
    at MessageBuilderBase._append (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/message_builder_base.js:117:15)
    at MessageBuilderBase._feed_messageChunk (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/message_builder_base.js:176:14)
    at PacketAssembler.<anonymous> (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/message_builder_base.js:52:14)
    at emitOne (events.js:116:13)
    at PacketAssembler.emit (events.js:211:7)
    at PacketAssembler.feed (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-packet-assembler/src/packet_assembler.js:105:14)
    at MessageBuilderBase.feed (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/message_builder_base.js:156:30)
    at ServerTCP_transport.<anonymous> (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-secure-channel/src/server/server_secure_channel_layer.js:340:37)
    at emitOne (events.js:116:13)
    at ServerTCP_transport.emit (events.js:211:7)
    at ServerTCP_transport._on_message_received (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/tcp_transport.js:193:14)
    at PacketAssembler.<anonymous> (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/tcp_transport.js:291:30)
server_secure_channel_layer   :115   xxxxx Server is now closing socket, without further notice
server_secure_channel_layer   :885   ServerSecureChannelLayer#close
tcp_transport                 :303    SOCKET CLOSE :  had_error = false  Transport 37
tcp_transport                 :320    SOCKET END :  null CLIENT  Transport 36
tcp_transport                 :255   Transport Connection ended  Transport 36
tcp_transport                 :263    bytesRead    =  28
tcp_transport                 :264    bytesWritten =  1869
tcp_transport                 :303    SOCKET CLOSE :  had_error = false  Transport 36
tcp_transport                 :306     remote address =  undefined   undefined   undefined
21 Feb 19:32:01 - [error] [OPCUA-IIoT-Connector:LOCAL SERVER] Error: _socket has been disconnected by third party
    at ClientTCP_transport.TCP_transport._on_socket_ended_message (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/tcp_transport.js:257:18)
    at Socket.<anonymous> (/Users/klaus/Development/github/node-red-contrib-iiot-opcua/node_modules/node-opcua-transport/src/tcp_transport.js:322:14)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
                Bytes Read :  384
             Bytes Written :  256
   time to receive request :  0.003531999999999243  sec
   time to process request :  0.43678199999999195  sec
   time to send response   :  0.0004840000000112923  sec
`

Is there some to do for the client with the pki package?
I set the cnf config for the server to my `NodeRED-IIoT-Server` and the client to `NodeRED-IIoT-Client` as the application name.

It works well from different path with the certs and keys of the installation process.
(node-opcua-client/certificates/...)

Maybe you have a hint for me, please!

Thank you!
Klaus

**Comment by biancode** [comment]
If the keys and certs are copied to the `node-opcua-client/certificates` folder it works well, maybe it needs a option to set the whole certificate path to get also the `config.js` and `cnf` ?

**Comment by biancode** [comment]
I did some more test and at the end just the 1024 client cert and key works - 2048 and 4096 does not work.

that works well:
![image](https://user-images.githubusercontent.com/4369867/36506530-38f2eb90-1757-11e8-9e78-0d4eea11b636.png)

these do not:
![image](https://user-images.githubusercontent.com/4369867/36506558-4a83db9e-1757-11e8-81be-7de7a4640191.png)

![image](https://user-images.githubusercontent.com/4369867/36506581-5a82b72c-1757-11e8-81f3-834d559b7f9c.png)

**Comment by biancode** [comment]
all key pairs and certs are built with the pki package

**Comment by erossignon** [comment]
* please do not forget to specify the node-opcua version that you're using when submitting an issue.

In order to work, certificates has to be trusted on the server side,
The way to do it much depends on the server itself. 
Can you confirm that  the certificate you use has been put to the trusted certificate list on the server side ?

**Comment by biancode** [comment]
No problems since v1.0.3 here
